# Generated by Django 3.2 on 2021-08-14 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('Role', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('Serial', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='Avatar')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.roles')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Workerdoc',
            fields=[
                ('Serialw', models.AutoField(primary_key=True, serialize=False)),
                ('Doc_name_w', models.CharField(max_length=50)),
                ('Sub_Date_w', models.DateTimeField()),
                ('class_name', models.CharField(max_length=50)),
                ('Filew', models.FileField(upload_to='Document')),
                ('Late', models.BooleanField()),
                ('Doc_path', models.CharField(max_length=50)),
                ('Owner_w', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.userdata')),
            ],
            options={
                'db_table': 'Worker Document',
            },
        ),
        migrations.CreateModel(
            name='Ownerdoc',
            fields=[
                ('Serialo', models.AutoField(primary_key=True, serialize=False)),
                ('Doc_name', models.CharField(max_length=50)),
                ('Post_Date', models.DateTimeField()),
                ('Sub_Date', models.DateTimeField()),
                ('File', models.FileField(upload_to='Doc')),
                ('class_name_O', models.CharField(max_length=50)),
                ('Cmnt', models.TextField()),
                ('Type', models.IntegerField()),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.userdata')),
            ],
            options={
                'db_table': 'OwnerDocument',
            },
        ),
        migrations.CreateModel(
            name='ClassGrp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=50)),
                ('Cowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.userdata')),
            ],
            options={
                'db_table': 'Class',
            },
        ),
    ]
