# Generated by Django 3.2 on 2021-08-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdoc',
            name='Doc_path',
            field=models.IntegerField(),
        ),
    ]
