# Generated by Django 3.2 on 2021-09-01 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_attended', models.DateField()),
                ('W_class', models.CharField(max_length=50)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.userdata')),
            ],
            options={
                'db_table': 'Attendance',
                'unique_together': {('Date_attended', 'Student')},
            },
        ),
    ]
