# Generated by Django 3.2 on 2021-09-02 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('aidi', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('Serialno', models.AutoField(primary_key=True, serialize=False)),
                ('Grade_c', models.CharField(max_length=1)),
                ('ownerd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.ownerdoc')),
            ],
        ),
    ]
