# Generated by Django 3.2 on 2021-09-03 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='workerd',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='first.workerdoc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='Grade_c',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('ownerd', 'workerd')},
        ),
        migrations.AlterModelTable(
            name='grade',
            table='Grade',
        ),
    ]
