# Generated by Django 3.2 on 2021-09-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_auto_20210904_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='ownerd',
            field=models.IntegerField(),
        ),
    ]
