# Generated by Django 3.2 on 2021-09-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_alter_grade_ownerd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='workerd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.userdata'),
        ),
    ]
